//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.UI.MVC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Een sterk getypeerde bronklasse waarmee u kunt zoeken naar gelokaliseerde tekenreeksen, enz.
    /// </summary>
    // Deze klasse wordt automatisch gegenereerd met de StronglyTypedResourceBuilder
    // klasse via een hulpprogramma zoals ResGen of Visual Studio.
    // Als u een lid wilt toevoegen of verwijderen, bewerkt u het .ResX-bestand en voert u ResGen opnieuw uit
    // met de optie /str, of u bouwt het VS-project opnieuw.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_nl() {
        }
        
        /// <summary>
        ///   Retourneert het exemplaar van ResourceManager dat in het cachegeheugen is opgeslagen en dat wordt gebruikt in deze klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAR.UI.MVC.App_GlobalResources.Resources.nl", typeof(Resources_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overschrijft de huidige CurrentUICulture-eigenschap voor alle
        ///   bronzoekacties waarvoor deze sterk getypeerde bronklasse wordt gebruikt.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeveer.
        /// </summary>
        public static string About_Time {
            get {
                return ResourceManager.GetString("About_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeveer een uur.
        /// </summary>
        public static string AboutOneHour {
            get {
                return ResourceManager.GetString("AboutOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeveer een minuut.
        /// </summary>
        public static string AboutOneMinute {
            get {
                return ResourceManager.GetString("AboutOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeveer een maand.
        /// </summary>
        public static string AboutOneMonth {
            get {
                return ResourceManager.GetString("AboutOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeveer een jaar.
        /// </summary>
        public static string AboutOneYear {
            get {
                return ResourceManager.GetString("AboutOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Boven 25.
        /// </summary>
        public static string Above25 {
            get {
                return ResourceManager.GetString("Above25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Een dag.
        /// </summary>
        public static string Aday {
            get {
                return ResourceManager.GetString("Aday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Voeg een grafiek toe..
        /// </summary>
        public static string AddAChart {
            get {
                return ResourceManager.GetString("AddAChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Voeg item toe.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bron toevoegen.
        /// </summary>
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Voeg SubPlatform toe.
        /// </summary>
        public static string AddSubPlatform {
            get {
                return ResourceManager.GetString("AddSubPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admin dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admins beheren.
        /// </summary>
        public static string AdminManagement {
            get {
                return ResourceManager.GetString("AdminManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Leeftijd.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Leeftijd.
        /// </summary>
        public static string AgeDistributionOfMentions {
            get {
                return ResourceManager.GetString("AgeDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Geleden.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts via email.
        /// </summary>
        public static string AlertsViaEmail {
            get {
                return ResourceManager.GetString("AlertsViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts via website.
        /// </summary>
        public static string AlertsViaWebsite {
            get {
                return ResourceManager.GetString("AlertsViaWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Partij-overzicht.
        /// </summary>
        public static string AllParties {
            get {
                return ResourceManager.GetString("AllParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politici-overzicht.
        /// </summary>
        public static string AllPoliticians {
            get {
                return ResourceManager.GetString("AllPoliticians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Thema-overzicht.
        /// </summary>
        public static string AllThemes {
            get {
                return ResourceManager.GetString("AllThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ga naar startpagina.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Staafgrafiek.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Basis grafiek.
        /// </summary>
        public static string BasicGraph {
            get {
                return ResourceManager.GetString("BasicGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Onder 25.
        /// </summary>
        public static string Below25 {
            get {
                return ResourceManager.GetString("Below25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Berekend volgens het aantal tweets..
        /// </summary>
        public static string CalculatedByAmountOfTweets {
            get {
                return ResourceManager.GetString("CalculatedByAmountOfTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Kan het items niet verwijderen..
        /// </summary>
        public static string CannotRemoveItem {
            get {
                return ResourceManager.GetString("CannotRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Categorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verander rol.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Data kiezen.
        /// </summary>
        public static string ChooseData {
            get {
                return ResourceManager.GetString("ChooseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Welke data wil u op uw grafiek laten zien?.
        /// </summary>
        public static string ChooseDataSubText {
            get {
                return ResourceManager.GetString("ChooseDataSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Grafiek kiezen.
        /// </summary>
        public static string ChooseGraph {
            get {
                return ResourceManager.GetString("ChooseGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Welk type grafiek wilt u laten zien?.
        /// </summary>
        public static string ChooseGraphSubText {
            get {
                return ResourceManager.GetString("ChooseGraphSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Kies een persoon, organisatie of thema..
        /// </summary>
        public static string ChoosePersonOrgTopic {
            get {
                return ResourceManager.GetString("ChoosePersonOrgTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Woonplaats.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vergelijk data met een ander persoon, organisatie of thema..
        /// </summary>
        public static string CompareDataPlaceholder {
            get {
                return ResourceManager.GetString("CompareDataPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vergelijkende grafiek.
        /// </summary>
        public static string ComparingGraph {
            get {
                return ResourceManager.GetString("ComparingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bevestig je account.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bevestig je account door hier te klikken..
        /// </summary>
        public static string ConfirmAccountClickingHere {
            get {
                return ResourceManager.GetString("ConfirmAccountClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vergeten wachtwoord bevestiging.
        /// </summary>
        public static string ConfirmForgotPassword {
            get {
                return ResourceManager.GetString("ConfirmForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Wachtwoord bevestigen.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bevestig wachtwoord reset.
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bevestig je email.
        /// </summary>
        public static string ConfirmYourEmail {
            get {
                return ResourceManager.GetString("ConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verbindt uw.
        /// </summary>
        public static string ConnectYour {
            get {
                return ResourceManager.GetString("ConnectYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Creeer Item.
        /// </summary>
        public static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aanmaak datum.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Huidig wachtwoord.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Geboortedatum.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Dagen.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijderen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijder account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Let op. Bij het verwijderen van uw account worden al uw grafieken, instellingen en voorkeuren verwijderd..
        /// </summary>
        public static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijder gebruiker.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Donutdiagram.
        /// </summary>
        public static string DonutChart {
            get {
                return ResourceManager.GetString("DonutChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Download JPG afbeelding.
        /// </summary>
        public static string DownloadJPGImage {
            get {
                return ResourceManager.GetString("DownloadJPGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Download PNG afbeelding.
        /// </summary>
        public static string DownloadPNGImage {
            get {
                return ResourceManager.GetString("DownloadPNGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Opleiding.
        /// </summary>
        public static string EducationDistributionOfMentions {
            get {
                return ResourceManager.GetString("EducationDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met E-mailadres.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met E-mailadres is verplicht..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Een e-mail is verzonden om uw wachtwoord te resetten..
        /// </summary>
        public static string EmailSentPasswordReset {
            get {
                return ResourceManager.GetString("EmailSentPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met E-mail ons.
        /// </summary>
        public static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vul uw e-mail in..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Externe login.
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Extravert.
        /// </summary>
        public static string Extrovert {
            get {
                return ResourceManager.GetString("Extrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mislukt.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vrouw.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vull de overige velden in en registreer..
        /// </summary>
        public static string FillTheRemainingFields {
            get {
                return ResourceManager.GetString("FillTheRemainingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Voornaam.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Volg deze persoon.
        /// </summary>
        public static string FollowThisPerson {
            get {
                return ResourceManager.GetString("FollowThisPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vergeten wachtwoord.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Wachtwoord vergeten?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Geslacht.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Geslacht.
        /// </summary>
        public static string GenderDistributionOfMentions {
            get {
                return ResourceManager.GetString("GenderDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Grafiek type.
        /// </summary>
        public static string GraphType {
            get {
                return ResourceManager.GetString("GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Hoger opgeleid.
        /// </summary>
        public static string HigherEducated {
            get {
                return ResourceManager.GetString("HigherEducated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bekijk welke politici trending zijn.
        /// </summary>
        public static string HomepageHeaderTitle {
            get {
                return ResourceManager.GetString("HomepageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Horizontale staafgrafiek.
        /// </summary>
        public static string HorizontalBarChart {
            get {
                return ResourceManager.GetString("HorizontalBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Uur.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ik ga akkoord met de voorwaarden..
        /// </summary>
        public static string IAgreeWithTheTermsAndCondition {
            get {
                return ResourceManager.GetString("IAgreeWithTheTermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Content importeren.
        /// </summary>
        public static string ImportContent {
            get {
                return ResourceManager.GetString("ImportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Importeer themas.
        /// </summary>
        public static string ImportThemes {
            get {
                return ResourceManager.GetString("ImportThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Over.
        /// </summary>
        public static string In_Time {
            get {
                return ResourceManager.GetString("In_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met In aantal vermeldingen..
        /// </summary>
        public static string InNumberOfMentions {
            get {
                return ResourceManager.GetString("InNumberOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Kruising waarde.
        /// </summary>
        public static string IntersectValue {
            get {
                return ResourceManager.GetString("IntersectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met In trending percentage..
        /// </summary>
        public static string InTrendingPercentage {
            get {
                return ResourceManager.GetString("InTrendingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Introvert.
        /// </summary>
        public static string Introvert {
            get {
                return ResourceManager.GetString("Introvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met is nu beschikbaar!.
        /// </summary>
        public static string IsNowAvailable {
            get {
                return ResourceManager.GetString("IsNowAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met is nu trending!.
        /// </summary>
        public static string IsNowTrending {
            get {
                return ResourceManager.GetString("IsNowTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Items beheren.
        /// </summary>
        public static string ItemManagement {
            get {
                return ResourceManager.GetString("ItemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Zojuist.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Kernwoorden.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Talen.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Achternaam.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Laatste verhalen.
        /// </summary>
        public static string LatestStories {
            get {
                return ResourceManager.GetString("LatestStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Minder dan een minuut geleden.
        /// </summary>
        public static string LessThenOneMinute {
            get {
                return ResourceManager.GetString("LessThenOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Lijngrafiek.
        /// </summary>
        public static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login mislukt.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login met uw.
        /// </summary>
        public static string LoginUsingYour {
            get {
                return ResourceManager.GetString("LoginUsingYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login met.
        /// </summary>
        public static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login met uw account.
        /// </summary>
        public static string LoginWithAccount {
            get {
                return ResourceManager.GetString("LoginWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Uitloggen.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Lager opgeleid.
        /// </summary>
        public static string LowerEducated {
            get {
                return ResourceManager.GetString("LowerEducated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Man.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Man.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Leden.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vermeldingen.
        /// </summary>
        public static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bericht.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Minuten.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Maanden.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Meer info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Meer informatie over.
        /// </summary>
        public static string MoreInfoAbout {
            get {
                return ResourceManager.GetString("MoreInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Meer mensen van.
        /// </summary>
        public static string MorePeopleFrom {
            get {
                return ResourceManager.GetString("MorePeopleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met N/B.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Negatief.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nieuw wachtwoord.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nee.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Abonneer jezelf op politici, partijen of thema&apos;s om te zien als zij trending zijn..
        /// </summary>
        public static string NoAlertsMessage {
            get {
                return ResourceManager.GetString("NoAlertsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Je hebt nog geen grafieken..
        /// </summary>
        public static string NoChartsYet {
            get {
                return ResourceManager.GetString("NoChartsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Geen data beschikbaar..
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nu kan je.
        /// </summary>
        public static string NowYouCan {
            get {
                return ResourceManager.GetString("NowYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Volgers.
        /// </summary>
        public static string NumberOfFollowers {
            get {
                return ResourceManager.GetString("NumberOfFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vermeldingen.
        /// </summary>
        public static string NumberOfMentions {
            get {
                return ResourceManager.GetString("NumberOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aantal vermeldingen.
        /// </summary>
        public static string NumberOfMentionsFull {
            get {
                return ResourceManager.GetString("NumberOfMentionsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Op sociale media.
        /// </summary>
        public static string OnSocialMedia {
            get {
                return ResourceManager.GetString("OnSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Optioneel.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Of.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Organisatie.
        /// </summary>
        public static string Organisation {
            get {
                return ResourceManager.GetString("Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Overige instellingen.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Kies optioneel enkele overige instellingen..
        /// </summary>
        public static string OtherSettingsSubText {
            get {
                return ResourceManager.GetString("OtherSettingsSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Pagina&apos;s beheren.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Pagina niet gevonden.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Partijen.
        /// </summary>
        public static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met De wachtwoorden komen niet overeen..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mensen die praten over.
        /// </summary>
        public static string PeopleWhoMention {
            get {
                return ResourceManager.GetString("PeopleWhoMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Persoonlijkheid.
        /// </summary>
        public static string PersonalityDistributionOfMentions {
            get {
                return ResourceManager.GetString("PersonalityDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Foto.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Taartdiagram.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politicus.
        /// </summary>
        public static string Politician {
            get {
                return ResourceManager.GetString("Politician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politici.
        /// </summary>
        public static string Politicians {
            get {
                return ResourceManager.GetString("Politicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Positief.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Privacy and veiligheid.
        /// </summary>
        public static string PrivacyAndSafety {
            get {
                return ResourceManager.GetString("PrivacyAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Profiel foto.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vraag en antwoord.
        /// </summary>
        public static string QuestionAndAnswer {
            get {
                return ResourceManager.GetString("QuestionAndAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Herstellen.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Herstel verwijderde gebruiker.
        /// </summary>
        public static string RecoverDeletedUser {
            get {
                return ResourceManager.GetString("RecoverDeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Herstel item.
        /// </summary>
        public static string RecoverItem {
            get {
                return ResourceManager.GetString("RecoverItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Onthoudt mij?.
        /// </summary>
        public static string RememberMeQuestion {
            get {
                return ResourceManager.GetString("RememberMeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijderen.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijder alert.
        /// </summary>
        public static string RemoveAlert {
            get {
                return ResourceManager.GetString("RemoveAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Data verwijderen.
        /// </summary>
        public static string RemoveData {
            get {
                return ResourceManager.GetString("RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verwijder item.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bron verwijderen.
        /// </summary>
        public static string RemoveSource {
            get {
                return ResourceManager.GetString("RemoveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verplicht.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Reset wachtwoord.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Je kan je wachtwoord resetten door hier te klikken..
        /// </summary>
        public static string ResetPasswordByClickingHere {
            get {
                return ResourceManager.GetString("ResetPasswordByClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Opslaan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Opgeslagen.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Zoek naar politici, partijen of thema&apos;s..
        /// </summary>
        public static string SearchbarPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Selecteer de bijbehorende organisatie.
        /// </summary>
        public static string SelectOrganisation {
            get {
                return ResourceManager.GetString("SelectOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Selecteer je woonplaats.
        /// </summary>
        public static string SelectYourCity {
            get {
                return ResourceManager.GetString("SelectYourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Selecteer je geslacht.
        /// </summary>
        public static string SelectYourGender {
            get {
                return ResourceManager.GetString("SelectYourGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verzenden.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Verzend een publiek Android bericht.
        /// </summary>
        public static string SendPublicAndroidMessage {
            get {
                return ResourceManager.GetString("SendPublicAndroidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Instellingen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bekijk alle alerts.
        /// </summary>
        public static string ShowAllAlerts {
            get {
                return ResourceManager.GetString("ShowAllAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Registreer.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Registreer als een nieuwe gebruiker..
        /// </summary>
        public static string SignupAsNewUser {
            get {
                return ResourceManager.GetString("SignupAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Registreer voor een nieuw account..
        /// </summary>
        public static string SignupForNewAccount {
            get {
                return ResourceManager.GetString("SignupForNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Registreer om te volgen.
        /// </summary>
        public static string SignupToFollow {
            get {
                return ResourceManager.GetString("SignupToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Social media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Er is iets misgegaan....
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Algemene instellingen.
        /// </summary>
        public static string SourceManagement {
            get {
                return ResourceManager.GetString("SourceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bronnen.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Blijf op de hoogte..
        /// </summary>
        public static string StayUpToDate {
            get {
                return ResourceManager.GetString("StayUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Deelplatformen beheren.
        /// </summary>
        public static string SubPlatformManagement {
            get {
                return ResourceManager.GetString("SubPlatformManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Abonneer.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Abonnementen.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Je bent succesvol ingelogd met.
        /// </summary>
        public static string SuccesfullyLoggedInWith {
            get {
                return ResourceManager.GetString("SuccesfullyLoggedInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Synchroniseer.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bedankt voor het bevestigen van uw e-mailadres..
        /// </summary>
        public static string ThanksEmailConfirm {
            get {
                return ResourceManager.GetString("ThanksEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Thema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Op.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Thema&apos;s.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Trending.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Onbekend.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Uitschrijven.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gebruiker.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ongeldige gebruikersnaam of wachtwoord..
        /// </summary>
        public static string UserController_Login_Ongeldige_inlogpoging_ {
            get {
                return ResourceManager.GetString("UserController_Login_Ongeldige_inlogpoging_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gebruikers beheren.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Weekly review.
        /// </summary>
        public static string WeeklyReview {
            get {
                return ResourceManager.GetString("WeeklyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Weekly Review via email.
        /// </summary>
        public static string WeeklyReviewViaEmail {
            get {
                return ResourceManager.GetString("WeeklyReviewViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vrouw.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Jaar.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Je hebt geen alerts..
        /// </summary>
        public static string YouHaveNoAlerts {
            get {
                return ResourceManager.GetString("YouHaveNoAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Uw.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Uw wachtwoord is gereset..
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
