//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.UI.MVC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Een sterk getypeerde bronklasse waarmee u kunt zoeken naar gelokaliseerde tekenreeksen, enz.
    /// </summary>
    // Deze klasse wordt automatisch gegenereerd met de StronglyTypedResourceBuilder
    // klasse via een hulpprogramma zoals ResGen of Visual Studio.
    // Als u een lid wilt toevoegen of verwijderen, bewerkt u het .ResX-bestand en voert u ResGen opnieuw uit
    // met de optie /str, of u bouwt het VS-project opnieuw.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Retourneert het exemplaar van ResourceManager dat in het cachegeheugen is opgeslagen en dat wordt gebruikt in deze klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAR.UI.MVC.App_GlobalResources.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overschrijft de huidige CurrentUICulture-eigenschap voor alle
        ///   bronzoekacties waarvoor deze sterk getypeerde bronklasse wordt gebruikt.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Environ.
        /// </summary>
        public static string About_Time {
            get {
                return ResourceManager.GetString("About_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Environ une heure.
        /// </summary>
        public static string AboutOneHour {
            get {
                return ResourceManager.GetString("AboutOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Environ une minute.
        /// </summary>
        public static string AboutOneMinute {
            get {
                return ResourceManager.GetString("AboutOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Environ un mois.
        /// </summary>
        public static string AboutOneMonth {
            get {
                return ResourceManager.GetString("AboutOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Environ un an.
        /// </summary>
        public static string AboutOneYear {
            get {
                return ResourceManager.GetString("AboutOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Plus de 25.
        /// </summary>
        public static string Above25 {
            get {
                return ResourceManager.GetString("Above25", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Compte.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Un jour.
        /// </summary>
        public static string Aday {
            get {
                return ResourceManager.GetString("Aday", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ajouter un graphique.
        /// </summary>
        public static string AddAChart {
            get {
                return ResourceManager.GetString("AddAChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ajouter une source.
        /// </summary>
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Adder un subplatformer.
        /// </summary>
        public static string AddSubPlatform {
            get {
                return ResourceManager.GetString("AddSubPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Administrateur.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Tableau de bord administrateur.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer administrateurs.
        /// </summary>
        public static string AdminManagement {
            get {
                return ResourceManager.GetString("AdminManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Âge.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Répartition par âge des mentions.
        /// </summary>
        public static string AgeDistributionOfMentions {
            get {
                return ResourceManager.GetString("AgeDistributionOfMentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Il y a .
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Notifications.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Notifications via e-mail .
        /// </summary>
        public static string AlertsViaEmail {
            get {
                return ResourceManager.GetString("AlertsViaEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Notifications sur le site internet.
        /// </summary>
        public static string AlertsViaWebsite {
            get {
                return ResourceManager.GetString("AlertsViaWebsite", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aperçu des partis.
        /// </summary>
        public static string AllParties {
            get {
                return ResourceManager.GetString("AllParties", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aperçu des politiciens.
        /// </summary>
        public static string AllPoliticians {
            get {
                return ResourceManager.GetString("AllPoliticians", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aperçu du sujet.
        /// </summary>
        public static string AllThemes {
            get {
                return ResourceManager.GetString("AllThemes", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Retour à la page d&apos;accueil.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique à barres.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique de base.
        /// </summary>
        public static string BasicGraph {
            get {
                return ResourceManager.GetString("BasicGraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Moins de 25.
        /// </summary>
        public static string Below25 {
            get {
                return ResourceManager.GetString("Below25", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Calculé par nombre des tweets.
        /// </summary>
        public static string CalculatedByAmountOfTweets {
            get {
                return ResourceManager.GetString("CalculatedByAmountOfTweets", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ne peut effacer pas l&apos;élément.
        /// </summary>
        public static string CannotRemoveItem {
            get {
                return ResourceManager.GetString("CannotRemoveItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Catégory.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Changer de rôle.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisir des données.
        /// </summary>
        public static string ChooseData {
            get {
                return ResourceManager.GetString("ChooseData", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Quelles données souhaitez-vous afficher sur votre graphique?.
        /// </summary>
        public static string ChooseDataSubText {
            get {
                return ResourceManager.GetString("ChooseDataSubText", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisir un graphique.
        /// </summary>
        public static string ChooseGraph {
            get {
                return ResourceManager.GetString("ChooseGraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Quel type de graphique souhaitez-vous afficher?.
        /// </summary>
        public static string ChooseGraphSubText {
            get {
                return ResourceManager.GetString("ChooseGraphSubText", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisissez une personne, une organisation ou un sujet..
        /// </summary>
        public static string ChoosePersonOrgTopic {
            get {
                return ResourceManager.GetString("ChoosePersonOrgTopic", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Résidence.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Comparer des données avec une autre personne, organisation ou sujet..
        /// </summary>
        public static string CompareDataPlaceholder {
            get {
                return ResourceManager.GetString("CompareDataPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique de comparaison.
        /// </summary>
        public static string ComparingGraph {
            get {
                return ResourceManager.GetString("ComparingGraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmer votre compte.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmez votre compte par cliquez ici..
        /// </summary>
        public static string ConfirmAccountClickingHere {
            get {
                return ResourceManager.GetString("ConfirmAccountClickingHere", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmer de oublié le mot de passe..
        /// </summary>
        public static string ConfirmForgotPassword {
            get {
                return ResourceManager.GetString("ConfirmForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmer votre mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmer le reset du mot de passe..
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirmer votre e-mail.
        /// </summary>
        public static string ConfirmYourEmail {
            get {
                return ResourceManager.GetString("ConfirmYourEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Connectez votre.
        /// </summary>
        public static string ConnectYour {
            get {
                return ResourceManager.GetString("ConnectYour", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Date de création.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mot de passe actuel.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Tableau de bord.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Date de naissance.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Jours.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enlever.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Effacez mon profil.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Attention! À enlevez votre account toutes les institutions, graphiques et préférences doivent effacer..
        /// </summary>
        public static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enlever utilisateur.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique de donut.
        /// </summary>
        public static string DonutChart {
            get {
                return ResourceManager.GetString("DonutChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Télécharger l&apos;image JPG.
        /// </summary>
        public static string DownloadJPGImage {
            get {
                return ResourceManager.GetString("DownloadJPGImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Télécharger l&apos;image PNG.
        /// </summary>
        public static string DownloadPNGImage {
            get {
                return ResourceManager.GetString("DownloadPNGImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met E-mail obligatoire.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Un e-mail est envoyé pour réinitialiser votre mot de passe..
        /// </summary>
        public static string EmailSentPasswordReset {
            get {
                return ResourceManager.GetString("EmailSentPasswordReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Envoyez un courriel.
        /// </summary>
        public static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Indiquez votre e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Connexion extérieure.
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met échoué.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Femme.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Indiquer les autres champs relatifs.
        /// </summary>
        public static string FillTheRemainingFields {
            get {
                return ResourceManager.GetString("FillTheRemainingFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Prénom.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Suivez cette personne.
        /// </summary>
        public static string FollowThisPerson {
            get {
                return ResourceManager.GetString("FollowThisPerson", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Oublié votre mot de passe.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Oublié votre mot de passe?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Genre.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Répartition par sexe des mentions.
        /// </summary>
        public static string GenderDistributionOfMentions {
            get {
                return ResourceManager.GetString("GenderDistributionOfMentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gestion générale.
        /// </summary>
        public static string GeneralManagement {
            get {
                return ResourceManager.GetString("GeneralManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Type de graphique.
        /// </summary>
        public static string GraphType {
            get {
                return ResourceManager.GetString("GraphType", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Page d&apos;acceuil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Regardez quel politiciens sont tendence..
        /// </summary>
        public static string HomepageHeaderTitle {
            get {
                return ResourceManager.GetString("HomepageHeaderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique à barres horizontal.
        /// </summary>
        public static string HorizontalBarChart {
            get {
                return ResourceManager.GetString("HorizontalBarChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Heures.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met J&apos;ai lu et accepté les modalités et conditions..
        /// </summary>
        public static string IAgreeWithTheTermsAndCondition {
            get {
                return ResourceManager.GetString("IAgreeWithTheTermsAndCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Importer contenu.
        /// </summary>
        public static string ImportContent {
            get {
                return ResourceManager.GetString("ImportContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met à.
        /// </summary>
        public static string In_Time {
            get {
                return ResourceManager.GetString("In_Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met En nombre de mentions..
        /// </summary>
        public static string InNumberOfMentions {
            get {
                return ResourceManager.GetString("InNumberOfMentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Valeur d&apos;intersection.
        /// </summary>
        public static string IntersectValue {
            get {
                return ResourceManager.GetString("IntersectValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met En pourcentage de tendance..
        /// </summary>
        public static string InTrendingPercentage {
            get {
                return ResourceManager.GetString("InTrendingPercentage", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met est maintenant disponible!.
        /// </summary>
        public static string IsNowAvailable {
            get {
                return ResourceManager.GetString("IsNowAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Est tendance.
        /// </summary>
        public static string IsNowTrending {
            get {
                return ResourceManager.GetString("IsNowTrending", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer des éléments.
        /// </summary>
        public static string ItemManagement {
            get {
                return ResourceManager.GetString("ItemManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Juste maintenant.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Langues.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nom de famille.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Les dernières histoires.
        /// </summary>
        public static string LatestStories {
            get {
                return ResourceManager.GetString("LatestStories", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Moins d&apos;une minute.
        /// </summary>
        public static string LessThenOneMinute {
            get {
                return ResourceManager.GetString("LessThenOneMinute", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique linéaire.
        /// </summary>
        public static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Lien.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Liens.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Se connecter.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Authentification a échoué.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Se connecter avec votre.
        /// </summary>
        public static string LoginUsingYour {
            get {
                return ResourceManager.GetString("LoginUsingYour", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Se connecter avec.
        /// </summary>
        public static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Se connecter avec votre compte.
        /// </summary>
        public static string LoginWithAccount {
            get {
                return ResourceManager.GetString("LoginWithAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Déconnecter.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Homme.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Homme.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Membres.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mentions.
        /// </summary>
        public static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mois.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Plus d&apos;informations.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Plus de gens de.
        /// </summary>
        public static string MorePeopleFrom {
            get {
                return ResourceManager.GetString("MorePeopleFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Négatif.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nouveau mot de passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aucune notification.
        /// </summary>
        public static string NoAlertsMessage {
            get {
                return ResourceManager.GetString("NoAlertsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Aucune graphique.
        /// </summary>
        public static string NoChartsYet {
            get {
                return ResourceManager.GetString("NoChartsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Pas de données disponibles..
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Maintenant vous pouvez.
        /// </summary>
        public static string NowYouCan {
            get {
                return ResourceManager.GetString("NowYouCan", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nombre d&apos;abonnés.
        /// </summary>
        public static string NumberOfFollowers {
            get {
                return ResourceManager.GetString("NumberOfFollowers", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mentions.
        /// </summary>
        public static string NumberOfMentions {
            get {
                return ResourceManager.GetString("NumberOfMentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nombre de mentions.
        /// </summary>
        public static string NumberOfMentionsFull {
            get {
                return ResourceManager.GetString("NumberOfMentionsFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sur les résaux sociaux.
        /// </summary>
        public static string OnSocialMedia {
            get {
                return ResourceManager.GetString("OnSocialMedia", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Optionnel.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ou.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Autres réglages.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisissez d&apos;autres paramètres graphiques optionnels..
        /// </summary>
        public static string OtherSettingsSubText {
            get {
                return ResourceManager.GetString("OtherSettingsSubText", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer des pages.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Page non trouvée.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Parties.
        /// </summary>
        public static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Les mots de passe ne corresponds pas..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graphique camembert.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politicien.
        /// </summary>
        public static string Politician {
            get {
                return ResourceManager.GetString("Politician", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politiciens.
        /// </summary>
        public static string Politicians {
            get {
                return ResourceManager.GetString("Politicians", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Positif.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confidentialité.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confidentialité et sécurité.
        /// </summary>
        public static string PrivacyAndSafety {
            get {
                return ResourceManager.GetString("PrivacyAndSafety", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Photo de profil.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Questions et réponses.
        /// </summary>
        public static string QuestionAndAnswer {
            get {
                return ResourceManager.GetString("QuestionAndAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Récupérer.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Récupérer un utilisateur enlevé.
        /// </summary>
        public static string RecoverDeletedUser {
            get {
                return ResourceManager.GetString("RecoverDeletedUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Récupérer un élément.
        /// </summary>
        public static string RecoverItem {
            get {
                return ResourceManager.GetString("RecoverItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Retenir moi.
        /// </summary>
        public static string RememberMeQuestion {
            get {
                return ResourceManager.GetString("RememberMeQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enlever.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enlever un notification.
        /// </summary>
        public static string RemoveAlert {
            get {
                return ResourceManager.GetString("RemoveAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Supprimer des données.
        /// </summary>
        public static string RemoveData {
            get {
                return ResourceManager.GetString("RemoveData", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enlever un élément.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Supprimer la source.
        /// </summary>
        public static string RemoveSource {
            get {
                return ResourceManager.GetString("RemoveSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Réinitialiser.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Réinitialisez votre mot de passe.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Réinitialisez votre mot de passe par cliquer ici..
        /// </summary>
        public static string ResetPasswordByClickingHere {
            get {
                return ResourceManager.GetString("ResetPasswordByClickingHere", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Rôle.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sauvegardé.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Cherchez des politiciens, des parties ou des sujets..
        /// </summary>
        public static string SearchbarPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisissez votre ville.
        /// </summary>
        public static string SelectYourCity {
            get {
                return ResourceManager.GetString("SelectYourCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choisisser votre genre.
        /// </summary>
        public static string SelectYourGender {
            get {
                return ResourceManager.GetString("SelectYourGender", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Préférences.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Montrez toutes les notifications.
        /// </summary>
        public static string ShowAllAlerts {
            get {
                return ResourceManager.GetString("ShowAllAlerts", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Inscrire.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Inscrire comme nouveau utilisateur.
        /// </summary>
        public static string SignupAsNewUser {
            get {
                return ResourceManager.GetString("SignupAsNewUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Inscrire avec nouveau compte.
        /// </summary>
        public static string SignupForNewAccount {
            get {
                return ResourceManager.GetString("SignupForNewAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Inscrire pour suivre.
        /// </summary>
        public static string SignupToFollow {
            get {
                return ResourceManager.GetString("SignupToFollow", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Médias sociaux.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Quelque chose a mal tourné....
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer général.
        /// </summary>
        public static string SourceManagement {
            get {
                return ResourceManager.GetString("SourceManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Restez à jour.
        /// </summary>
        public static string StayUpToDate {
            get {
                return ResourceManager.GetString("StayUpToDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer sub-plateforme.
        /// </summary>
        public static string SubPlatformManagement {
            get {
                return ResourceManager.GetString("SubPlatformManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Abonner.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Abonnements.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Connecté en tant que .
        /// </summary>
        public static string SuccesfullyLoggedInWith {
            get {
                return ResourceManager.GetString("SuccesfullyLoggedInWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Synchroniser.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Merci pour confirmer votre e-mail..
        /// </summary>
        public static string ThanksEmailConfirm {
            get {
                return ResourceManager.GetString("ThanksEmailConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sujet.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Titre.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sur.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sujets.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Tendance.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Inconnu.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Désabonner.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Utilisateur.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Nom ou mot de passe invalide.
        /// </summary>
        public static string UserController_Login_Ongeldige_inlogpoging_ {
            get {
                return ResourceManager.GetString("UserController_Login_Ongeldige_inlogpoging_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gérer d&apos;utilisateurs.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Revue hebdomadaire.
        /// </summary>
        public static string WeeklyReview {
            get {
                return ResourceManager.GetString("WeeklyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Revue hebdomadaire via e-mail..
        /// </summary>
        public static string WeeklyReviewViaEmail {
            get {
                return ResourceManager.GetString("WeeklyReviewViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Femme.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met An.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Vous n&apos;avez pas de notifications..
        /// </summary>
        public static string YouHaveNoAlerts {
            get {
                return ResourceManager.GetString("YouHaveNoAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Votre.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Votre mot de passe est réinitialisé..
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
