//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.UI.MVC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Een sterk getypeerde bronklasse waarmee u kunt zoeken naar gelokaliseerde tekenreeksen, enz.
    /// </summary>

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourneert het exemplaar van ResourceManager dat in het cachegeheugen is opgeslagen en dat wordt gebruikt in deze klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAR.UI.MVC.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overschrijft de huidige CurrentUICulture-eigenschap voor alle
        ///   bronzoekacties waarvoor deze sterk getypeerde bronklasse wordt gebruikt.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met About.
        /// </summary>
        public static string About_Time {
            get {
                return ResourceManager.GetString("About_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met About an hour.
        /// </summary>
        public static string AboutOneHour {
            get {
                return ResourceManager.GetString("AboutOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met About a minute.
        /// </summary>
        public static string AboutOneMinute {
            get {
                return ResourceManager.GetString("AboutOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met About a month.
        /// </summary>
        public static string AboutOneMonth {
            get {
                return ResourceManager.GetString("AboutOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met About a year.
        /// </summary>
        public static string AboutOneYear {
            get {
                return ResourceManager.GetString("AboutOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Above 25.
        /// </summary>
        public static string Above25 {
            get {
                return ResourceManager.GetString("Above25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met A day.
        /// </summary>
        public static string Aday {
            get {
                return ResourceManager.GetString("Aday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Add a chart..
        /// </summary>
        public static string AddAChart {
            get {
                return ResourceManager.GetString("AddAChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Add source.
        /// </summary>
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Add SubPlatform.
        /// </summary>
        public static string AddSubPlatform {
            get {
                return ResourceManager.GetString("AddSubPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admin dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Admin management.
        /// </summary>
        public static string AdminManagement {
            get {
                return ResourceManager.GetString("AdminManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Age distribution of mentions.
        /// </summary>
        public static string AgeDistributionOfMentions {
            get {
                return ResourceManager.GetString("AgeDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts by email.
        /// </summary>
        public static string AlertsViaEmail {
            get {
                return ResourceManager.GetString("AlertsViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Alerts on website.
        /// </summary>
        public static string AlertsViaWebsite {
            get {
                return ResourceManager.GetString("AlertsViaWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met All parties.
        /// </summary>
        public static string AllParties {
            get {
                return ResourceManager.GetString("AllParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met All politicians.
        /// </summary>
        public static string AllPoliticians {
            get {
                return ResourceManager.GetString("AllPoliticians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met All topics.
        /// </summary>
        public static string AllThemes {
            get {
                return ResourceManager.GetString("AllThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Back to home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Bar chart.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Basic graph.
        /// </summary>
        public static string BasicGraph {
            get {
                return ResourceManager.GetString("BasicGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Below 25.
        /// </summary>
        public static string Below25 {
            get {
                return ResourceManager.GetString("Below25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Calculated via the amount of tweets..
        /// </summary>
        public static string CalculatedByAmountOfTweets {
            get {
                return ResourceManager.GetString("CalculatedByAmountOfTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Cannot remove item..
        /// </summary>
        public static string CannotRemoveItem {
            get {
                return ResourceManager.GetString("CannotRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Change role.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choose data.
        /// </summary>
        public static string ChooseData {
            get {
                return ResourceManager.GetString("ChooseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met What data do you want to show on your graph?.
        /// </summary>
        public static string ChooseDataSubText {
            get {
                return ResourceManager.GetString("ChooseDataSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choose graph.
        /// </summary>
        public static string ChooseGraph {
            get {
                return ResourceManager.GetString("ChooseGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met What type of graph would you like to display?.
        /// </summary>
        public static string ChooseGraphSubText {
            get {
                return ResourceManager.GetString("ChooseGraphSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choose person, organisation or topic..
        /// </summary>
        public static string ChoosePersonOrgTopic {
            get {
                return ResourceManager.GetString("ChoosePersonOrgTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Compare data with another person, organisation or topic..
        /// </summary>
        public static string CompareDataPlaceholder {
            get {
                return ResourceManager.GetString("CompareDataPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Comparing graph.
        /// </summary>
        public static string ComparingGraph {
            get {
                return ResourceManager.GetString("ComparingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirm your account..
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirm your account by clicking here..
        /// </summary>
        public static string ConfirmAccountClickingHere {
            get {
                return ResourceManager.GetString("ConfirmAccountClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Forgotten password confirmation.
        /// </summary>
        public static string ConfirmForgotPassword {
            get {
                return ResourceManager.GetString("ConfirmForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirm reset password.
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Confirm your email.
        /// </summary>
        public static string ConfirmYourEmail {
            get {
                return ResourceManager.GetString("ConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Connect your.
        /// </summary>
        public static string ConnectYour {
            get {
                return ResourceManager.GetString("ConnectYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Warning. When deleting your account al your settings, graphs and widgets will be removed..
        /// </summary>
        public static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Delete user..
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Donut chart.
        /// </summary>
        public static string DonutChart {
            get {
                return ResourceManager.GetString("DonutChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Download JPG image.
        /// </summary>
        public static string DownloadJPGImage {
            get {
                return ResourceManager.GetString("DownloadJPGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Download PNG image.
        /// </summary>
        public static string DownloadPNGImage {
            get {
                return ResourceManager.GetString("DownloadPNGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met An email has been sent to reset your password..
        /// </summary>
        public static string EmailSentPasswordReset {
            get {
                return ResourceManager.GetString("EmailSentPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Email us.
        /// </summary>
        public static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Enter your email..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met External login.
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Complete the remaining fields and signup..
        /// </summary>
        public static string FillTheRemainingFields {
            get {
                return ResourceManager.GetString("FillTheRemainingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met First name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Follow this person..
        /// </summary>
        public static string FollowThisPerson {
            get {
                return ResourceManager.GetString("FollowThisPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Forgot your password?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Gender distribution of mentions.
        /// </summary>
        public static string GenderDistributionOfMentions {
            get {
                return ResourceManager.GetString("GenderDistributionOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met General management.
        /// </summary>
        public static string GeneralManagement {
            get {
                return ResourceManager.GetString("GeneralManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Graph type.
        /// </summary>
        public static string GraphType {
            get {
                return ResourceManager.GetString("GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met See which politicians are trending.
        /// </summary>
        public static string HomepageHeaderTitle {
            get {
                return ResourceManager.GetString("HomepageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Horizontal bar chart.
        /// </summary>
        public static string HorizontalBarChart {
            get {
                return ResourceManager.GetString("HorizontalBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met I agree with the terms and conditions..
        /// </summary>
        public static string IAgreeWithTheTermsAndCondition {
            get {
                return ResourceManager.GetString("IAgreeWithTheTermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Import content.
        /// </summary>
        public static string ImportContent {
            get {
                return ResourceManager.GetString("ImportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met In.
        /// </summary>
        public static string In_Time {
            get {
                return ResourceManager.GetString("In_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met In number of mentions..
        /// </summary>
        public static string InNumberOfMentions {
            get {
                return ResourceManager.GetString("InNumberOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Intersect value.
        /// </summary>
        public static string IntersectValue {
            get {
                return ResourceManager.GetString("IntersectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met in trending percentage..
        /// </summary>
        public static string InTrendingPercentage {
            get {
                return ResourceManager.GetString("InTrendingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met is now available!.
        /// </summary>
        public static string IsNowAvailable {
            get {
                return ResourceManager.GetString("IsNowAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met is now trending!.
        /// </summary>
        public static string IsNowTrending {
            get {
                return ResourceManager.GetString("IsNowTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Item management.
        /// </summary>
        public static string ItemManagement {
            get {
                return ResourceManager.GetString("ItemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Latest stories.
        /// </summary>
        public static string LatestStories {
            get {
                return ResourceManager.GetString("LatestStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Less then on minute.
        /// </summary>
        public static string LessThenOneMinute {
            get {
                return ResourceManager.GetString("LessThenOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Line chart.
        /// </summary>
        public static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login using your.
        /// </summary>
        public static string LoginUsingYour {
            get {
                return ResourceManager.GetString("LoginUsingYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login with.
        /// </summary>
        public static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Login with your account..
        /// </summary>
        public static string LoginWithAccount {
            get {
                return ResourceManager.GetString("LoginWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Man.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mentions.
        /// </summary>
        public static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met More info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met More people from.
        /// </summary>
        public static string MorePeopleFrom {
            get {
                return ResourceManager.GetString("MorePeopleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Subscribe yourself to politicians, parties or topics to see when they are trending..
        /// </summary>
        public static string NoAlertsMessage {
            get {
                return ResourceManager.GetString("NoAlertsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met You don&apos;t have any charts yet..
        /// </summary>
        public static string NoChartsYet {
            get {
                return ResourceManager.GetString("NoChartsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met No data available..
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Now you can.
        /// </summary>
        public static string NowYouCan {
            get {
                return ResourceManager.GetString("NowYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Followers.
        /// </summary>
        public static string NumberOfFollowers {
            get {
                return ResourceManager.GetString("NumberOfFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Mentions.
        /// </summary>
        public static string NumberOfMentions {
            get {
                return ResourceManager.GetString("NumberOfMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Number of mentions.
        /// </summary>
        public static string NumberOfMentionsFull {
            get {
                return ResourceManager.GetString("NumberOfMentionsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met On social media.
        /// </summary>
        public static string OnSocialMedia {
            get {
                return ResourceManager.GetString("OnSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Organisation.
        /// </summary>
        public static string Organisation {
            get {
                return ResourceManager.GetString("Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Other settings.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Choose other optional graph settings..
        /// </summary>
        public static string OtherSettingsSubText {
            get {
                return ResourceManager.GetString("OtherSettingsSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Page management.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Parties.
        /// </summary>
        public static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Pie chart.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politician.
        /// </summary>
        public static string Politician {
            get {
                return ResourceManager.GetString("Politician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Politicians.
        /// </summary>
        public static string Politicians {
            get {
                return ResourceManager.GetString("Politicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Privacy and safety.
        /// </summary>
        public static string PrivacyAndSafety {
            get {
                return ResourceManager.GetString("PrivacyAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Profile picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Question and answer.
        /// </summary>
        public static string QuestionAndAnswer {
            get {
                return ResourceManager.GetString("QuestionAndAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Recover deleted user..
        /// </summary>
        public static string RecoverDeletedUser {
            get {
                return ResourceManager.GetString("RecoverDeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Recover item..
        /// </summary>
        public static string RecoverItem {
            get {
                return ResourceManager.GetString("RecoverItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remember me?.
        /// </summary>
        public static string RememberMeQuestion {
            get {
                return ResourceManager.GetString("RememberMeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remove alert.
        /// </summary>
        public static string RemoveAlert {
            get {
                return ResourceManager.GetString("RemoveAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remove data.
        /// </summary>
        public static string RemoveData {
            get {
                return ResourceManager.GetString("RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remove item..
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Remove source.
        /// </summary>
        public static string RemoveSource {
            get {
                return ResourceManager.GetString("RemoveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met You can reset your password by clicking here..
        /// </summary>
        public static string ResetPasswordByClickingHere {
            get {
                return ResourceManager.GetString("ResetPasswordByClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Search for politicians, parties or topics..
        /// </summary>
        public static string SearchbarPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Select your city..
        /// </summary>
        public static string SelectYourCity {
            get {
                return ResourceManager.GetString("SelectYourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Select your gender.
        /// </summary>
        public static string SelectYourGender {
            get {
                return ResourceManager.GetString("SelectYourGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Show all alerts.
        /// </summary>
        public static string ShowAllAlerts {
            get {
                return ResourceManager.GetString("ShowAllAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Signup as a new user..
        /// </summary>
        public static string SignupAsNewUser {
            get {
                return ResourceManager.GetString("SignupAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Signup for a new account..
        /// </summary>
        public static string SignupForNewAccount {
            get {
                return ResourceManager.GetString("SignupForNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Signup to follow.
        /// </summary>
        public static string SignupToFollow {
            get {
                return ResourceManager.GetString("SignupToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Social media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Something went wrong....
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Source management.
        /// </summary>
        public static string SourceManagement {
            get {
                return ResourceManager.GetString("SourceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Stay up-to-date..
        /// </summary>
        public static string StayUpToDate {
            get {
                return ResourceManager.GetString("StayUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Subplatform management.
        /// </summary>
        public static string SubPlatformManagement {
            get {
                return ResourceManager.GetString("SubPlatformManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met You have successfully logged in with.
        /// </summary>
        public static string SuccesfullyLoggedInWith {
            get {
                return ResourceManager.GetString("SuccesfullyLoggedInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Synchronize.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Thank you for confirming your email address..
        /// </summary>
        public static string ThanksEmailConfirm {
            get {
                return ResourceManager.GetString("ThanksEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Topics.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Trending.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Unsubscribe.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Incorrect username or password..
        /// </summary>
        public static string UserController_Login_Ongeldige_inlogpoging_ {
            get {
                return ResourceManager.GetString("UserController_Login_Ongeldige_inlogpoging_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met User management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Weekly review.
        /// </summary>
        public static string WeeklyReview {
            get {
                return ResourceManager.GetString("WeeklyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Weekly Review by email.
        /// </summary>
        public static string WeeklyReviewViaEmail {
            get {
                return ResourceManager.GetString("WeeklyReviewViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Woman.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met You have no alerts..
        /// </summary>
        public static string YouHaveNoAlerts {
            get {
                return ResourceManager.GetString("YouHaveNoAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met Your password has been reset..
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
